### ISSUE TITLE
Expose BuiltinHelpFormatter to allow customization of option rendering

### ISSUE THREAD

**Issue by snicoll** [pholser/jopt-simple#68]
Currently a short option is detected when it is represented by a single letter. All other options are considered as long options (i.e. with the double hyphen notation).

There are numerous cases where it's legit to have a short options with two characters (`-bv` for instance). I tried to add a support for this in Spring Boot and I don't see anything that would prevent that. The reason I am asking here is that the help has no notion of this and `BuiltinHelpFormatter` is package protected so I can't really tune that except if I copy/paste the whole class.

It would be nice if the logic that define if it's a short option (currently `option.length() ==1`) would be configurable.

**Comment by pholser** [comment]
@snicoll Branch issues/68/expose-builtin-help-formatter has an altered version of `BuiltinHelpFormatter` that makes a number of formatting helper methods `protected` instead of `private`. It also introduces a method `optionLeader(String)` that decides what to prepend an option with. By default, it decides between '-' and '--' depending on the length of the given option indicator.

If you would, checkout this branch, build, and see whether this suits your needs. If so, I'll invest some more time in Javadoc'ing the class, especially being careful to document what behaviors the default impls guarantee.

Thanks!

**Comment by snicoll** [comment]
Awesome, will do tomorrow

**Comment by snicoll** [comment]
@pholser I had a look to the changes and `optionLeader` is doing exactly what I want.  Thanks!

**Comment by pholser** [comment]
@snicoll Excellent. I'll move forward with documenting the behaviors of the exposed methods. Expect to see this stuff in a 4.9 snapshot soon. I appreciate your feedback!

**Comment by snicoll** [comment]
Awesome!

**Comment by pholser** [comment]
Merged into branch 4.x.
