### ISSUE TITLE
missing parse() exception

### ISSUE THREAD

**Issue by XSven** [pholser/jopt-simple#99]
Hi Paul,

I have an issue/question that is similar to #34. In the old issue you stated

>     The other thing to note is that the conversion of an option argument
>     doesn't occur until you ask for the value. So parse() might not raise a
>     exception, but OptionSet().valueOf() might.

Having defined this
```
parser.accepts("c").withRequiredArg().ofType(Integer.class);
parser.accepts("l").withRequiredArg().ofType(Integer.class);
```
in my program I would have expected that parse() raises an exception, if I am calling my program with the parameters

-l -c 1

because the -l option misses the required argument. Instead of this OptionSet().valueOf("l") raises the exception

Cannot parse argument '-c' of option l

My interpretation of this message is that '-c' is used as an argument to the '-l' option and cannot be converted to an integer. I don't understand why an option ('-c') is used as an argument for another option ('-l') that has withRequiredArg() turned on. I would have expected that parse()  raises an exception like

Option l misses the required argument 

By the way changing the parser to a POSIXly correct behaviour doesn't matter.

Kind regards
Sven

**Comment by XSven** [comment]
Hi Paul,

would you mind providing some feedback with respect to this issue.

Thx and kind regards
Sven

**Comment by pholser** [comment]
@XSven I apologize for the late reply.

In the very early days of JOpt Simple, there was no argument type conversion. Arguments of options were always of type `String`. In fact, if I remember correctly, there were no `OptionSpec`s back then.

As such, the parsing behavior for options that require arguments makes sense: if the parser encounters an option that requires an argument, the next argument on the command line becomes the option's argument. The following Bash script that uses `getopt` demonstrates this:

```
#!/bin/bash

while getopts c:l: arg ; do
    case $arg in
    c)    echo "c = $OPTARG";;
    l)    echo "l = $OPTARG";;
    ?)    echo "unexpected flag";; 
    esac
done

shift $(($OPTIND - 1))
printf "Remaining arguments are: %s\n" "$*"
```

Invoked as `x.sh -l -c 2`, the output is:

```
l = -c
Remaining arguments are: 2
```

Now, since the time when we added `OptionSpec`s and argument type conversion, we have not changed the parsing behavior; type checking is still deferred until when you ask for the option's argument. The parser doesn't get involved in deciding whether `-l` is getting an argument that is type-convertible to `Integer`; it calmly lets `-c` be the argument of the option, and when you go to retrieve `valueOf("l")`, the type conversion exception happens then.

In practice, I don't imagine this causes too much consternation. I was imagining that the latent typing problem (i.e. `-c` is not type-convertible to be the `Integer` argument of `-l`) would get detected pretty early in `main()` or argument-handling code near the top of the call chain; further, adding all the type checking during parsing complicates parsing more than I think is worth the effort.

I hope this explanation helps.

**Comment by XSven** [comment]
Hi Paul,

thanks for the detailed feedback. Your bash script example tells me that the implemented kind of option parsing should be considered a standard. Sorry that it didn't come into my mind to test script based option parsing by my own, especially because I am quite familiar with scripting. I will close this issue now.

Thx again and kind regards
Sven
